from data import Location

QUESTIONS = [
    "How often do you come here?",
    "What is there to eat here?",
    "Have you been here before?",
    "Would this location smell good?",
    "Is this place kid-friendly?",
    "Is there a lot of noise in this place?",
    "What time of day is the busiest here?",
    "Do you need a reservation to visit?",
    "What kind of clothing do people typically wear here?",
    "How far is this location from the nearest public transportation?",
    "Are most people here happy?",
]

# Examples answers for the question: "How often do you come here?"
EXAMPLE_ANSWER = {
    Location.BLANTON_MUSEUM: "A few times a year",
    Location.HARRY_RANSOM_CENTER: "A few times a year",
    Location.LBJ_LIBRARY: "A few times a year",
    Location.FLAWN_ACADEMIC_CENTER: "Every day",
    Location.ART_BUILDING_AND_MUSEUM: "Every day",
    Location.GATES_DELL_COMPLEX: "Every day",
    Location.CHRISTIAN_GREEN_GALLERY: "A few times a month",
    Location.FINE_ARTS_LIBRARY: "A few times a week",
    Location.DARRELL_K_ROYAL_TEXAS_MEMORIAL_STADIUM: "Several times a year",
    Location.GREGORY_GYM: "Every day",
    Location.TEXAS_MEMORIAL_MUSEUM: "A few times a year",
    Location.UT_TOWER: "A few times a year",
    Location.LITTLEFIELD_FOUNTAIN: "Every day",
    Location.TURTLE_POND: "A few times a week",
    Location.THE_DRAG: "Every day",
    Location.NORMAN_HACKERMAN_BUILDING: "Every day",
    Location.WCP_STUDENT_ACTIVITY_CENTER: "Every day",
    Location.TEXAS_STATE_CAPITOL: "A few times a year",
    Location.MOUNT_BONNELL_AND_MAYFIELD_PARK: "Every once in a while",
    Location.BARTON_SPRINGS: "Every once in a while",
    Location.ZILKER_PARK: "Every week",
    Location.LAKE_AUSTIN: "Every once in a while",
    Location.LADY_BIRD_JOHNSON_WILDFLOWER_CENTER: "A few times a year",
    Location.ZILKER_BOTANICAL_GARDEN: "A few times a year",
    Location.CONGRESS_AVENUE_BRIDGE: "A few times a week",
    Location.SOUTH_CONGRESS: "A few times a month",
}

EXAMPLE_BAD_ANSWER = {
    Location.BLANTON_MUSEUM: "Every day",
    Location.HARRY_RANSOM_CENTER: "Every day",
    Location.LBJ_LIBRARY: "Every day",
    Location.FLAWN_ACADEMIC_CENTER: "Never",
    Location.ART_BUILDING_AND_MUSEUM: "Never",
    Location.GATES_DELL_COMPLEX: "Never",
    Location.CHRISTIAN_GREEN_GALLERY: "Every day",
    Location.FINE_ARTS_LIBRARY: "Never",
    Location.DARRELL_K_ROYAL_TEXAS_MEMORIAL_STADIUM: "Every day",
    Location.GREGORY_GYM: "Never",
    Location.TEXAS_MEMORIAL_MUSEUM: "Every day",
    Location.UT_TOWER: "Every day",
    Location.LITTLEFIELD_FOUNTAIN: "Never",
    Location.TURTLE_POND: "Never",
    Location.THE_DRAG: "Never",
    Location.NORMAN_HACKERMAN_BUILDING: "Never",
    Location.WCP_STUDENT_ACTIVITY_CENTER: "Never",
    Location.TEXAS_STATE_CAPITOL: "Every day",
    Location.MOUNT_BONNELL_AND_MAYFIELD_PARK: "Every day",
    Location.BARTON_SPRINGS: "Every day",
    Location.ZILKER_PARK: "Never",
    Location.LAKE_AUSTIN: "Every day",
    Location.LADY_BIRD_JOHNSON_WILDFLOWER_CENTER: "Every day",
    Location.ZILKER_BOTANICAL_GARDEN: "Every day",
    Location.CONGRESS_AVENUE_BRIDGE: "Never",
    Location.SOUTH_CONGRESS: "Every day",
}
